[package]
name = "seye_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
queues = "1.1.0"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
memory-stats = { version = "1.2.0", features = ["always_use_statm"] }
libc = "0.2"
